default:
  image:
    name: registry.gitlab.com/anilist-cicd/anilist-infra/ci-image:1.1
    entrypoint: [""]

variables:
  TF_ROOT: "terraform"
  ANSIBLE_ROOT: "ansible"

  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

  AWS_REGION: "eu-north-1"
  AWS_DEFAULT_REGION: "eu-north-1"

  ANSIBLE_SSM_BUCKET: "songhai9-anime-review-ansible-ssm-0909-eu-north-1"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

stages:
  - validate
  - plan
  - apply
  - configure
  - verify


.aws_oidc:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: sts.amazonaws.com

  before_script:
    - |
      aws_sts_output=$(aws sts assume-role-with-web-identity \
        --role-arn "$AWS_ROLE_ARN" \
        --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}" \
        --web-identity-token "$GITLAB_OIDC_TOKEN" \
        --duration-seconds 3600 \
        --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
        --output text)

    - export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" $aws_sts_output)


terraform_validate:
  stage: validate

  script:
    - terraform -chdir="$TF_ROOT" fmt -check -recursive
    - terraform -chdir="$TF_ROOT" init -backend=false
    - terraform -chdir="$TF_ROOT" validate


ansible_validate:
  stage: validate

  script:
    - ansible-galaxy collection install -r "$ANSIBLE_ROOT/requirements.yml"

    - |
      cat > /tmp/inventory.ini <<EOF
      [control_plane]
      control-plane ansible_host=127.0.0.1

      [workers]
      worker-1 ansible_host=127.0.0.1
      worker-2 ansible_host=127.0.0.1

      [k8s_nodes:children]
      control_plane
      workers
      EOF

    - ansible-playbook
        -i /tmp/inventory.ini
        --syntax-check
        "$ANSIBLE_ROOT/playbooks/site.yml"


terraform_plan:
  extends: .aws_oidc
  stage: plan

  script:
    - terraform -chdir="$TF_ROOT" init
    - terraform -chdir="$TF_ROOT" plan -out=tfplan
    - terraform -chdir="$TF_ROOT" show -no-color tfplan > plan.txt

  artifacts:
    paths:
      - terraform/tfplan
      - terraform/plan.txt
    expire_in: 1 day


terraform_apply:
  extends: .aws_oidc
  stage: apply

  needs:
    - job: terraform_plan
      artifacts: true

  resource_group: anime-review-infra

  script:
    - terraform -chdir="$TF_ROOT" init
    - terraform -chdir="$TF_ROOT" apply -auto-approve tfplan

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual

  allow_failure: false

configure_cluster:
  extends: .aws_oidc
  stage: configure

  needs:
    - job: terraform_apply

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

  script:
    - ansible-galaxy collection install -r "$ANSIBLE_ROOT/requirements.yml"

    - terraform -chdir="$TF_ROOT" init

    - bash "$ANSIBLE_ROOT/scripts/generate_inventory.sh"

    - |
      ansible-playbook \
        -i "$ANSIBLE_ROOT/inventory/inventory.ini" \
        "$ANSIBLE_ROOT/playbooks/site.yml"