[bastion]
16.192.105.78

[frontend]
10.0.1.64

[backend]
10.0.2.246

[database]
10.0.3.171

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/anime-review

[private:children]
frontend
backend
database

[private:vars]
ansible_ssh_common_args='-o ProxyJump=ubuntu@16.192.105.78'
