default:
  image:
    name: registry.gitlab.com/anilist-cicd/anilist-infra/ci-image:1.0
    entrypoint: [""]
    

.aws_oidc:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: sts.amazonaws.com

  before_script:
    - >
      aws_sts_output=$(aws sts assume-role-with-web-identity
      --role-arn "$AWS_ROLE_ARN"
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token "$GITLAB_OIDC_TOKEN"
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text)

    - export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" $aws_sts_output)
    - aws sts get-caller-identity

workflow:
  name: Update infra
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

stages:
  - validate
  - plan
  - provision
  - configure
  - test

validating_job:
  extends: .aws_oidc
  stage: validate
  script:
    - cd legacy/vm/terraform
    - terraform init
    - terraform fmt -check
    - terraform validate

planning_job:
  extends: .aws_oidc
  stage: plan
  script:
    - cd legacy/vm/terraform
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - legacy/vm/terraform/tfplan
    expire_in: 1 hour

provisioning_job:
  extends: .aws_oidc
  stage: provision
  needs:
    - job: planning_job
      artifacts: true
  script:
    - cd legacy/vm/terraform
    - terraform init
    - terraform apply -auto-approve tfplan

configuring_job:
  extends: .aws_oidc
  stage: configure

  needs:
    - provisioning_job

  rules:
    - if: "$IMAGE_TAG"

  script:
    - terraform -chdir=legacy/vm/terraform init
    - bash legacy/vm/ansible/scripts/generate_inventory.sh

    - mkdir -p ~/.ssh
    - cp "$SSH_PRIVATE_KEY" ~/.ssh/anime-review
    - chmod 600 ~/.ssh/anime-review

    - |
      ssh \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -i ~/.ssh/anime-review \
        -l ubuntu \
        "$(terraform -chdir=legacy/vm/terraform output -raw bastion_eip)" \
        "echo BASTION_OK"

    - ansible-galaxy collection install -r legacy/vm/ansible/requirements.yml

    - cat legacy/vm/ansible/inventory/inventory.ini

    - |
      ansible private \
        -i legacy/vm/ansible/inventory/inventory.ini \
        -m wait_for_connection \
        -a "timeout=300" \
        --vault-password-file "$ANSIBLE_VAULT_PASSWORD_FILE"

    - |
      ansible private \
        -i legacy/vm/ansible/inventory/inventory.ini \
        -m ping \
        --vault-password-file "$ANSIBLE_VAULT_PASSWORD_FILE"

    - |
      ansible-playbook \
        -i legacy/vm/ansible/inventory/inventory.ini \
        --vault-password-file "$ANSIBLE_VAULT_PASSWORD_FILE" \
        -e "image_tag=$IMAGE_TAG" \
        legacy/vm/ansible/playbooks/site.yml