registry_url: registry.gitlab.com

registry_image_prefix: "registry.gitlab.com/songhai9/manga-app"

registry_username: "{{ vault_registry_username }}"
registry_password: "{{ vault_registry_password }}"
